name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create symbolic link for requirements
      run: ln -s ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: ./requirements.txt
    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
