name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
   # Step 2: Create symbolic link for requirements.txt
    - name: Create symbolic link for requirements.txt
      run: ln -s ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Set up Node.js
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: **/requirements.txt
